// Generated by CoffeeScript 1.9.0
(function() {
  var Backbone, BootstrapFormMixin, FormMixin, bootstrapField, forms, index, _,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  index = require("./index");

  forms = require("forms");

  Backbone = require("backbone");

  _ = require("underscore");

  FormMixin = (function() {
    function FormMixin() {}

    FormMixin.prototype.form = null;

    FormMixin.prototype.events = {
      "submit form": "handleFormSubmit"
    };

    FormMixin.prototype.initialize = function(options) {
      if (options == null) {
        options = {};
      }
      if (options.form) {
        this.form = options.form;
      }
      if (options.renderFunc) {
        return this.renderFunc = options.renderFunc;
      }
    };

    FormMixin.prototype.getContext = function(context) {
      if (context == null) {
        context = {};
      }
      if (!context.form) {
        return context.form = this.renderForm(context);
      }
    };

    FormMixin.prototype.getForm = function(context) {
      return this.form;
    };

    FormMixin.prototype.renderForm = function(context) {
      var form, html;
      if (context == null) {
        context = {};
      }
      form = this.getForm(context);
      if (this.renderFunc) {
        html = form.toHTML(this.renderFunc.bind(this));
      } else {
        html = form.toHTML();
      }
      return html;
    };

    FormMixin.prototype.handleFormSubmit = function(e) {
      var data, form, row, _i, _len, _ref;
      e.preventDefault();
      data = {};
      _ref = this.$(e.target).serializeArray();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        data[row.name] = row.value;
      }
      form = this.getForm().bind(data);
      return form.validate((function(_this) {
        return function(err, form) {
          console.log("error", err, form);
          if (form.isValid()) {
            _this.trigger("form:valid", form);
            return typeof _this.formValid === "function" ? _this.formValid(form) : void 0;
          } else {
            _this.trigger("form:invalid", form);
            return typeof _this.formInvalid === "function" ? _this.formInvalid(form) : void 0;
          }
        };
      })(this));
    };

    FormMixin.prototype.formInvalid = function(form) {
      return this.render({
        form: form
      });
    };

    return FormMixin;

  })();

  bootstrapField = function(name, object) {
    var error, inputSize, label, labelSize, validationclass, widget;
    object.widget.classes = object.widget.classes || [];
    object.widget.classes.push('form-control');
    inputSize = this.inputSize || "col-md-6";
    labelSize = this.labelSize || "col-md-6";
    label = object.labelHTML(name);
    label = ("<label class='" + labelSize + " control-label'>") + label + "</label>";
    if (object.error) {
      error = '<div class="alert alert-error help-block">' + object.error + '</div>';
    } else {
      error = '';
    }
    validationclass = object.value && !object.error && 'has-success' || '';
    validationclass = object.error && 'has-error' || validationclass;
    widget = object.widget.toHTML(name, object);
    widget = ("<div class='" + inputSize + "'>") + widget + "</div>";
    return '<div class="form-group ' + validationclass + '">' + label + widget + error + '</div>';
  };

  BootstrapFormMixin = (function(_super) {
    __extends(BootstrapFormMixin, _super);

    function BootstrapFormMixin() {
      return BootstrapFormMixin.__super__.constructor.apply(this, arguments);
    }

    BootstrapFormMixin.prototype.renderFunc = bootstrapField;

    BootstrapFormMixin.prototype.formInvalid = function(form) {
      var field, input, name, _ref, _results;
      this.$el.find(".help-block").remove();
      _ref = form.fields;
      _results = [];
      for (name in _ref) {
        field = _ref[name];
        input = this.$el.find("[name=" + name + "]");
        if (field.error) {
          input.after("<span class=\"help-block\">" + field.error + "</span>");
          _results.push(input.parents(".form-group").addClass("has-error"));
        } else {
          _results.push(input.parents(".form-group").removeClass("has-error"));
        }
      }
      return _results;
    };

    return BootstrapFormMixin;

  })(FormMixin);

  module.exports = {
    mixins: {
      FormMixin: FormMixin,
      BootstrapFormMixin: BootstrapFormMixin
    }
  };

}).call(this);
