// Generated by CoffeeScript 1.9.0
(function() {
  var Backbone, ContextMixin, MixinView, NunjucksMixin, NunjucksView, SelectorMixin, _,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  Backbone = require("backbone");

  _ = require("underscore");

  MixinView = (function(_super) {
    __extends(MixinView, _super);

    function MixinView() {
      return MixinView.__super__.constructor.apply(this, arguments);
    }

    MixinView.prototype.mixins = [];

    MixinView.prototype.initialize = function(options) {
      var mixin, _i, _len, _ref, _ref1;
      if (options == null) {
        options = {};
      }
      this.options = options;
      if (this.options.mixins) {
        this.mixins = options.mixins;
      }
      _ref = this.mixins;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mixin = _ref[_i];
        _.defaults(this, mixin.prototype);
        if ((_ref1 = mixin.prototype.initialize) != null) {
          _ref1.apply(this, [options]);
        }
        if (mixin.prototype.events) {
          this.events = _.defaults(this.events || {}, mixin.prototype.events);
        }
      }
      return this.trigger("mixins:loaded", this);
    };

    return MixinView;

  })(Backbone.View);


  /*
    provides a "getContext" function that sends a "view:context" signal
    and calls the "getContext" function of all other mixins
   */

  ContextMixin = (function() {
    function ContextMixin() {}

    ContextMixin.prototype.getContext = function(context) {
      var mixin, _i, _len, _ref, _ref1;
      if (context == null) {
        context = {};
      }
      this.trigger("view:context", context);
      if (this.mixins) {
        _ref = this.mixins;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          mixin = _ref[_i];
          if ((_ref1 = mixin.getContext) != null) {
            _ref1.bind(this)(context);
          }
        }
      }
      return context;
    };

    return ContextMixin;

  })();


  /*
  selects items on the property `ui`
   */

  SelectorMixin = (function() {
    function SelectorMixin() {}

    SelectorMixin.prototype.initialize = function(options) {
      if (options.ui) {
        this.ui = options.ui;
      }
      if (this.ui) {
        if (!this._ui) {
          return this._ui = _.clone(this.ui);
        }
      }
    };

    SelectorMixin.prototype.setupUI = function() {
      var name, selector, _ref, _results;
      if (this._ui) {
        _ref = this._ui;
        _results = [];
        for (name in _ref) {
          selector = _ref[name];
          _results.push(this.ui[name] = this.$el.find(selector));
        }
        return _results;
      }
    };

    return SelectorMixin;

  })();


  /*
  Renders a nunjucks tempalte
  You can set the template on the class or pass it to the constructor
   */

  NunjucksMixin = (function() {
    function NunjucksMixin() {}

    NunjucksMixin.prototype.mixin = function(options) {
      if (options.template) {
        return this.template = options.template;
      }
    };

    NunjucksMixin.prototype.renderNunjucksTemplate = function(context) {
      var html, template;
      if (context == null) {
        context = {};
      }
      if (this.getTemplate) {
        template = this.getTemplate();
      } else {
        template = this.template;
      }
      if (!template.compiled) {
        template.compile();
      }
      if (this.getContext) {
        context = this.getContext(context);
      }
      html = template.render(context);
      this.setElement(html);
      return this;
    };

    return NunjucksMixin;

  })();


  /*
  Renders a nunjucks tempalte
  You can set the template on the class or pass it to the constructor
   */

  NunjucksView = (function(_super) {
    __extends(NunjucksView, _super);

    function NunjucksView() {
      return NunjucksView.__super__.constructor.apply(this, arguments);
    }

    NunjucksView.prototype.mixins = [NunjucksMixin, SelectorMixin];

    NunjucksView.prototype.render = function(context) {
      if (context == null) {
        context = {};
      }
      this.renderNunjucksTemplate(context);
      this.setupUI();
      return this;
    };

    return NunjucksView;

  })(MixinView);

  module.exports = {
    mixins: {
      NunjucksMixin: NunjucksMixin,
      SelectorMixin: SelectorMixin
    },
    views: {
      MixinView: MixinView,
      NunjucksView: NunjucksView
    }
  };

}).call(this);
