// Generated by CoffeeScript 1.7.1
(function() {
  var mixins, mod, mods, views, _, _i, _len;

  _ = require("underscore");

  mods = [require('./views/index'), require('./views/forms'), require('./views/list')];

  mixins = {};

  views = {};

  for (_i = 0, _len = mods.length; _i < _len; _i++) {
    mod = mods[_i];
    _.extend(mixins, mod.mixins);
    _.extend(views, mod.views);
  }

  module.exports = {
    mixins: mixins,
    views: views
  };

}).call(this);
